### ISSUE TITLE
Camera jitter after import in Blender

### ISSUE THREAD

**Issue by mfeldt** [imagiscope/EarthStudioTools#9]
After importing the json file, the camera has a position and an Euler rotation at every frame. Looking at the curves in the editor, they seem very smooth. However, the camera itself behaves quite shaky in Blender, and objects placed in the 3D environment consequently bounce around a bit against the image background.

My guess is, this is a blender issue - somehow the "every frame is a key frame" leads to a loss in precision when pointing the camera and consequently to the shakiness.

**Comment by imagiscope** [comment]
Additionally, scenes that travel over 3000km can lose some precision due to
limited decimal values in Blender.

Rob

**Comment by mfeldt** [comment]
Well, this one just travels a couple of a hundred metres, and it looks as if the precision loss is in the angles. 

Any experience with short distances? 

Or maybe 2 pi issues?

**Comment by imagiscope** [comment]
Short distances are generally fine. Try a new JSON file. When something
weird happens, I usually go to a new JSON first and it usually fixes the
problem.

Rob

**Comment by mfeldt** [comment]
I've narrowed it down to the z-coordinate of the camera for some reason changing only in steps of ~40mm or not at all...

Then I changed "something" in Blender about the interpolation modes for the keyframe graphs, re-imported the json and now the issue is gone. The mysteries of Blender...

**Comment by imagiscope** [comment]
This sometime happens due to the JSON file being downloaded with the render
from Google Earth Studio (it has a bug). Go back in GES and export the JSON
file (overwrite) and re-import into Blender.

Let me know if this works for you.

Rob
